### ISSUE TITLE
View Comments

### ISSUE THREAD

**Issue by naomi-mali** [naomi-mali/api-retrospective#15]
As a user, I can view comments on posts so that I can read the discussions around the content.

## Acceptance Criterias:

- ### Comments are displayed under each post.
- ### User can see the number of comments on a post.
- ### Comments are sorted in chronological order.

## Tasks:

- [ ] Task 1: Implement API endpoint for fetching comments.
- [ ] Task 2: Ensure frontend displays comments with posts.
- [ ] Task 3: Optimize loading time for comment sections.
