### ISSUE TITLE
Add Site Favicon

### ISSUE THREAD

**Issue by naomi-mali** [naomi-mali/api-retrospective#38]
As a developer, I can add a favicon to the site so that the brand is recognizable in browser tabs.

## Acceptance Criteria:

- ### Favicon displays correctly in browser tabs.
- ### Favicon is visible on all pages of the site.
- ### Favicon meets design specifications.

## Tasks:

- [ ] Task 1: Create or select a favicon image.
- [ ] Task 2: Add favicon to the site’s HTML head section.
- [ ] Task 3: Test favicon visibility in different browsers.
