### ISSUE TITLE
View User Profile

### ISSUE THREAD

**Issue by naomi-mali** [naomi-mali/api-retrospective#5]
As a user I can view my profile so that I can see my displayed  information and posts.

## Acceptance Criterias :

- ### User can access their profile page after logging in.
- ### Profile displays user information, posts.
- ### Profile information is fetched and displayed correctly.

## Tasks :

-  [ ] Task 1 : Implement API endpoint to fetch user profile details.
- [ ] Task 2 : Create frontend layout for the profile page.
- [ ] Task 3 : Ensure profile data is updated in real-time.
