### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by naomi-mali** [naomi-mali/api-retrospective#7]
As a developer, I can set up the project structure so that I can begin development efficiently.

## Acceptance Criterias :

- ### The project is initialized with Django and Django REST Framework.
- ### All necessary dependencies are installed.
- ### Project folder structure is organized and documented.

## Tasks :

- [ ] Task 1 : Create a new Django project and applications.
- [ ]  Task 2 : Install Django REST Framework and other required packages.
- [ ] Task 3 : Set up version control with Git.
